# Generated by Django 4.1.3 on 2022-12-05 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WS', 'Winter-Semester'), ('SS', 'Sommer-Semester')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialisationTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('graduate_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.graduateprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('learning_objective', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('graduate_programs', models.ManyToManyField(to='base.graduateprogram')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.lecturer')),
                ('semesters', models.ManyToManyField(to='base.semester')),
                ('specialisation_tracks', models.ManyToManyField(to='base.specialisationtrack')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
