# Generated by Django 4.1.3 on 2022-12-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_favourites_alter_module_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateprogram',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='base.module'),
        ),
    ]
