# Generated by Django 4.1.3 on 2022-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_semester_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='base.module'),
        ),
    ]
