# Generated by Django 4.1.3 on 2022-12-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_student_favourites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduateprogram',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='specialisationtrack',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='module',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.lecturer'),
        ),
        migrations.AlterField(
            model_name='module',
            name='specialisation_tracks',
            field=models.ManyToManyField(blank=True, null=True, to='base.specialisationtrack'),
        ),
    ]
