# Generated by Django 4.1.3 on 2022-12-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_graduateprogram_options_alter_lecturer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='specialisation_tracks',
            field=models.ManyToManyField(blank=True, to='base.specialisationtrack'),
        ),
    ]
