# Generated by Django 4.1.3 on 2022-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LECTURER'), (2, 'STUDENT'), (3, 'ADMIN')]),
        ),
    ]
